name: Daily update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      STRINGS: ${{ steps.set_matrix.outputs.STRINGS}}
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v2
      - name: Determine folders
        id: set_matrix
        run: |
         echo "STRINGS=$(ls source/ | head -n 2 | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT
  update_sources:
    runs-on: ubuntu-latest
    needs: prepare
    strategy:
      matrix:
        nom: ${{ fromJson(needs.prepare.outputs.STRINGS) }}
    steps:
      - name: Setup Python environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Checkout current repo
        uses: actions/checkout@v2
      - name: Install mdsplit
        run: |
          curl https://bootstrap.pypa.io/get-pip.py --output get-pip.py
          python3 get-pip.py
          pip3 install mdsplit
          mkdir -p source_md/
      - name: Download source files
        run: |
            nom=${{ matrix.nom}}
            git subtree pull --prefix source/"$nom" "https://archeo-lex.fr/codes/$nom" texte --squash
            git add .
            if git commit -m "updating $nom";  then
                echo "Le code $nom est déjà à jour"
                exit 0
            else
                mkdir source_md/"$nom"
                sed -E 's/(#{6})#{1,}/\1/g' source/"$nom"/"$nom".md > source_md/"$nom"/"$nom"_1.md
                sed -E 's/^#(#*) ([^:]+) :.*/#\1 \2/' source_md/"$nom"/"$nom"_1.md > source_md/"$nom"/"$nom".md
                mdsplit source_md/"$nom"/"$nom".md --max-level 6 --output "$nom"-out
                rm -rf "$nom"
                mv "$nom"-out "$nom"
                find $nom -type f ! -name 'Article*' -delete
                sleep 1
                git add .
                git commit -m "updating $nom";
                git push
            fi
